apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: "Project for applications"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      name: 'in-cluster'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
