routes:
  - hostname: argo.suspectsoftware.com
    service: http://argocd-server.argocd.svc.cluster.local:80
  - hostname: harbor.suspectsoftware.com
    service: http://harbor.harbor.svc.cluster.local:80
