routes:
  - hostname: suspectsoftware.com
    service: http://web.app-web.svc.cluster.local:80
  - hostname: cotv.dk
    service: http://web.app-web.svc.cluster.local:80
  - hostname: callofthevoid.dk
    service: http://web.app-web.svc.cluster.local:80
