apiVersion: v1
kind: Secret
metadata:
  name: cluster-secret-platform-services-test
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: production
type: Opaque
stringData:
  name: in-cluster
  server: "https://kubernetes.default.svc"
