charts:
  - chart: external-secrets
    version: "1.0.0"
    repositoryUrl: "https://charts.external-secrets.io"

  - chart: cert-manager
    version: "1.18.2"
    repositoryUrl: https://charts.jetstack.io

  - chart: prometheus
    releaseName: prometheus
    namespace: prometheus
    version: "27.28.0"
    repositoryUrl: "https://prometheus-community.github.io/helm-charts"

  - chart: gateway-helm
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    version: "v1.6.1"
    repositoryUrl: "docker.io/envoyproxy"
