fullnameOverride: argocd

global:
  domain: argo.suspectsoftware.com

controller:
  replicas: 1
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  pdb:
    enabled: false
    minAvailable: 1
  podLabels: {}

dex:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

redis:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

repoServer:
  replicas: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  pdb:
    enabled: true
    minAvailable: 1

applicationSet:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  pdb:
    enabled: false
    minAvailable: 1

server:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  pdb:
    enabled: false
    minAvailable: 1

  podLabels: {}

  service:
    annotations:
      load-balancer.hetzner.cloud/location: hel1  # Ensures the load balancer is in the same network zone as your nodes
      load-balancer.hetzner.cloud/use-private-ip: "true"  # Routes traffic between the load balancer and nodes through the private network
    type: LoadBalancer
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https
    # -- Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
    ## Ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
    externalTrafficPolicy: Cluster
    sessionAffinity: None # Supports `ClientIP` and `None`

  # httproute:
  #   enabled: true
  #   hostnames:
  #     - argo.suspectsoftware.com
  #   parentRefs:
  #     - group: gateway.networking.k8s.io
  #       kind: Gateway
  #       name: envoy-gateway
  #       namespace: envoy-gateway-system

configs:
  params:
    server.insecure: true
    server.log.level: debug
  rbac:
    create: true
    policy.default: ""
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, applications, *, *, allow
      p, role:org-admin, clusters, *, *, allow
      p, role:org-admin, repositories, *, *, allow
      p, role:org-admin, applicationsets, *, */*, allow
      p, role:org-admin, logs, *, */*, allow
      p, role:org-admin, exec, *, */*, allow
      p, role:org-admin, projects, *, *, allow
      p, role:org-admin, *, *, *, allow
      p, role:org-admin, *, *, */*, allow
      g, rasmus@suspectsoftware.com, role:org-admin
    scopes: '[groups, email]' # Required to allow both groups AND users to be defined in policy.csv
  cm:
    url: https://argo.suspectsoftware.com
    create: true
    admin.enabled: true
    exec.enabled: true
    application.resourceTrackingMethod: annotation
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: $dex.google.clientID
          clientSecret: $dex.google.clientSecret
        type: oidc
        id: google
        name: Google
