# Install the cert-manager CRDs, it is recommended to not use Helm to manage the CRDs
installCRDs: true

config:
  # Enable Gateway API support
  # https://cert-manager.io/docs/usage/gateway/
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true

extraArgs:
  - --issuer-ambient-credentials=true
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,208.67.222.222:53

webhook:
  validatingWebhookConfiguration:
    # Configure spec.namespaceSelector for validating webhooks.
    # +docs:property
    namespaceSelector:
      matchExpressions:
        - key: "cert-manager.io/disable-validation"
          operator: "NotIn"
          values:
            - "true"
        - key: control-plane
          operator: NotIn
          values:
            - "true"
