expose:
  type: clusterIP
  tls:
    enabled: false

externalURL: https://harbor.suspectosftware.com

existingSecretAdminPassword: harbor-secrets
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
existingSecretSecretKey: harbor-secrets

persistence:
  enabled: true
  resourcePolicy: keep
  persistentVolumeClaim:
    registry:
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 100Gi
    jobservice:
      jobLog:
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
    database:
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 5Gi
    redis:
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 2Gi

updateStrategy:
  type: Recreate

trivy:
  enabled: false

ipFamily:
  ipv6:
    enabled: false
  ipv4:
    enabled: true
