apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/suspectsoftware/argocd-management.git'
        revision: HEAD
        directory:
          - path: "apps/*"
  template:
    metadata:
      name: 'user-app-{{path.basename}}'
      namespace: 'app-{{path.basename}}'
    spec:
      project: team-alpha
      source:
        repoURL: 'https://github.com/suspectsoftware/argocd-management.git'
        targetRevision: HEAD
        path: charts/webapp
        helm:
          valueFiles:
            - '../../apps/{{path.basename}}/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'app-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
