apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/suspectsoftware/argocd-applications.git
        revision: HEAD
        directories:
          - path: "*"
  template:
    metadata:
      name: 'user-app-{{ .path.basename }}'
    spec:
      project: team-alpha
      sources:
        - repoURL: https://github.com/suspectsoftware/argocd-management.git
          targetRevision: HEAD
          path: charts/webapp
          helm:
            valueFiles:
              - '$values/{{ .path.path }}/values.yaml'
        - repoURL: https://github.com/suspectsoftware/argocd-applications.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: 'app-{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
