apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/suspectsoftware/argocd-management.git'
        revision: HEAD
        files:
          - path: "apps/*.yaml"
  template:
    metadata:
      name: 'user-app-{{path.basenameNormalized}}'
      namespace: '{{path.basenameNormalized}}'
    spec:
      project: team-alpha
      source:
        repoURL: 'https://github.com/suspectsoftware/argocd-management.git'
        targetRevision: HEAD
        path: charts/webapp
        helm:
          valueFiles:
            - '../../{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'app-{{path.basenameNormalized}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
