apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: in-cluster
  sources:
    - repoURL: "https://github.com/suspectsoftware/argocd-management.git"
      path: config/applicationsets
    - repoURL: "https://github.com/suspectsoftware/argocd-management.git"
      path: config/root
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
