apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-1password-credentials
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: eso-1password-credentials
    template:
      type: Opaque
      data:
        token: "{{ .token | toString }}"
  data:
    - secretKey: token
      remoteRef:
        key: 1password-service-account-token/password
