apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-webhook
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: argocd-secret # Merge into existing secret
    creationPolicy: Merge
    template:
      type: Opaque
      data:
        webhook.github.secret: "{{ .Webhook | toString }}"
  data:
    - secretKey: Webhook
      remoteRef:
        key: argocd-server-webhook/secret
