apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: tunnel-token
    template:
      type: Opaque
      data:
        token: "{{ .tunnelToken | toString }}"
  data:
    - secretKey: tunnelToken
      remoteRef:
        key: argo-cloudflared/tunnel-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            - run
            - --url
            - http://argocd-server.argocd.svc.cluster.local:80
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 5
            periodSeconds: 10
