apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-store
spec:
  provider:
    onepasswordSDK:
      vault: kubernetes-argocd
      auth:
        serviceAccountSecretRef:
          name: eso-1password-credentials
          namespace: external-secrets
          key: token
